import Link from 'next/link';
import { Droplet } from 'lucide-react';

export default function Terms() {
  return (
    <div className="min-h-screen bg-[#060b16] text-white px-4 py-12">
      <div className="max-w-3xl mx-auto">
        <div className="flex items-center gap-2 mb-10">
          <Droplet className="w-7 h-7 text-cyan-400 fill-cyan-400/20" />
          <span className="text-xl font-bold text-cyan-400">Hydronyx</span>
        </div>

        <h1 className="text-3xl font-bold text-white mb-2">Terms of Service</h1>
        <p className="text-gray-400 text-sm mb-10">Last updated: April 2026</p>

        <div className="space-y-8 text-gray-300 leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Hydronyx ("the Service"), you agree to be bound by these Terms of Service.
              If you do not agree to these terms, you may not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">2. Description of Service</h2>
            <p>
              Hydronyx provides AI-powered groundwater analysis, forecasting, and policy simulation tools.
              All predictions and simulations are based on statistical models and historical data.
              Results are indicative only and should not replace professional hydrological assessments.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">3. Disclaimer of Warranties</h2>
            <p>
              The Service is provided "as is" without warranties of any kind. Groundwater forecasts,
              policy simulations, and optimization results carry inherent uncertainty and should be
              used as decision-support tools only — not as definitive predictions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">4. Limitation of Liability</h2>
            <p>
              Hydronyx and its developers shall not be liable for any damages arising from reliance
              on forecasts or recommendations generated by the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">5. User Accounts</h2>
            <p>
              You are responsible for maintaining the confidentiality of your account credentials.
              You agree not to share your account or use the Service for unauthorized or illegal purposes.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">6. Changes to Terms</h2>
            <p>
              We reserve the right to modify these terms at any time. Continued use of the Service
              after changes constitutes acceptance of the updated terms.
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-cyan-500/20 flex gap-6 text-sm text-gray-400">
          <Link href="/privacy" className="hover:text-cyan-400 transition">Privacy Policy</Link>
          <Link href="/login" className="hover:text-cyan-400 transition">Back to Sign In</Link>
        </div>
      </div>
    </div>
  );
}
